mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "root"
  dbname: "classicmodels"

postgresql:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "Password"
  dbname: "migration_postgres"

mongodb:
  host: "localhost"
  port: 27017
  user: "admin"
  password: "password"
  dbname: "migration_mongodb"
  #if uri is provided, it will override individual settings
  #uri: "mongodb://admin:password@localhost:27017/migration_mongodb"

sqlfile_path: "/home/susheel/learning/go/src/Work/datamigrationtool/mysqlsampledatabase.sql"
